### ISSUE TITLE
Cannot get it to work

### ISSUE THREAD

**Issue by raphaelfournier** [marvinkreis/rofi-json-dict#1]
Hello,

I have used other rofi plugins from you but I am struggling to make this one work. 
I have cloned the FreeDicts repo, and use `convert-dict` to get the right JSON format. My `.local/share/rofi-json-dicts/` has only one dict, `eng-fra.json`. 
I have tried the following command:
`rofi -modi json-dict -show json-dict -json-dict-path "/home/raph/.local/share/rofi-json-dicts/eng-fra.json" -json-dict-mode 0`
It outputs a blank `json-dict` prompt in rofi, as if it does not find the dict file. I have tried shorter versions of the command, but to no avail. I have looked at the source and found that the option  seems to be `dict-path` instead of `json-dict-path`, but it does not work either. 

Do you have any idea on what could be wrong with my config?

**Comment by marvinkreis** [comment]
Oh, it seems I forgot to change the command line arguments in the source. I'll update that right away.

The `-json-dict-path` argument takes the directory of the dictionaries, so in this case `/home/raph/.local/share/rofi-json-dicts`.

I converted `eng-fra` dictionary myself and put it in the default path, which worked for me.
Here's the command I used: ` rofi -modi json-dict -show json-dict -json-dict-path "${HOME}/.local/share/rofi-json-dicts" -json-dict-mode 0`

Also, a blank prompt as you open the plugin is normal, as the translation is only searched once the enter key is pressed (actually, an option to "search as you type" may be a good idea).

**Comment by raphaelfournier** [comment]
"Also, a blank prompt as you open the plugin is normal, as the translation is only searched once the enter key is pressed (actually, an option to "search as you type" may be a good idea)."
Oh! I am sorry, it works now, I probably did test this far, expecting a `search as you type` behavior. Thank you very much, for the plugin and the quick answer!
